spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-batch-in-action
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: user
    password: password
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always